# Generated by Django 3.1.5 on 2021-02-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20210202_1114'),
        ('carts', '0003_auto_20210202_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, through='carts.CartItem', to='items.Item'),
        ),
    ]
