# Generated by Django 3.1.5 on 2021-01-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptions',
            new_name='description',
        ),
    ]
